package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class resultDisplayController {
	@FXML
	private Button refresh;
	@FXML
	private Label easyHigh;
	@FXML
	private Label mediumHigh;
	@FXML
	private Label hardHigh;
	@FXML
	private Label easyWin;
	@FXML
	private Label easyLoss;
	@FXML
	private Label mediumWin;
	@FXML
	private Label mediumLoss;
	@FXML
	private Label hardWin;
	@FXML
	private Label hardLoss;
	
	public void seteasyHigh(String s) {
		easyHigh.setText(s);
	}

	// Event Listener on Button[#refresh].onAction
	@FXML
	public void wipeHistory(ActionEvent event) {
		// TODO Autogenerated
	}
}
